version: '3.8'

services:
  web:
    build: .
    command: gunicorn bakery_pos_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - sqlite_data:/app/db
    ports:
      - "8000:8000"
    env_file:
      - ./.env

volumes:
  static_volume:
  sqlite_data: