# Generated by Django 5.1.6 on 2025-03-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_customer_alter_sale_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'cash'), ('CARD', 'card')], max_length=10),
        ),
    ]
